name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_job:
    name: Hello Message
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Echo Hello Message
        run: echo "Hi, I am from COSC 1209 class (on ${{ matrix.os }})"

  build_java_app:
    name: Build Java App
    needs: hello_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: List build artifacts
        run: ls -l build/libs/  # Debugging step

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Java-App-Artifact
          path: build/libs/*

  build_docker_image:
    name: Build Docker Image
    needs: build_java_app
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true  # Fixed issue

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/your-image-name:latest
